### PR TITLE
Parent instead of offset parent

### PR DESCRIPTION
**Pull request by sQu1rr**
Since we won't go beyond parent no need for offset parent
Performance update: don't scroll-update if parent is not visible
moved scroll listener to window object instead of document (didn't work
correctly on firefox) - window scroll seems to be crossbrowser solution

### CODE REVIEW

**Comment by ppowalowski** [comment]
Hey,

thanks for your effort. Can you further explain where the benefit of using parent is? Obviously if parent is not positioned the affected element should reference first positioned element (which is offset parent) for calculations, not?

Scroll handler with window makes sense.

**Comment by sQu1rr** [comment]
i don't see a reason for offset parent. why can't i use static element as parent? what benefit does positioned element has over static?
here is the example of what this change accomplishes: parent does not limit the sticky-div https://jsfiddle.net/sQu1rr/zsqc6sfc/
here is with the change: https://jsfiddle.net/sQu1rr/8rvw6d5u/1/
here is positioned parent with absolute positioning. why is it even allowed? https://jsfiddle.net/sQu1rr/Lrwsupjx/1/
my point is that static should be allowed to be parent - nothing's wrong with it + in your own docs you say: "default: '' // uses first parent if empty" (wrapperSelector)

**Comment by ppowalowski** [comment]
Great many thanks for your PR and explanation with examples.
I need to dive into it – from what I see, it seems to work. When I have time I’ll go through the code and update.

Thanks

**Comment by ppowalowski** [comment]
Ok, I got it.
There is no reason for not using parent at this point. Also I couldn't produce any misbehavior according to this change.

-> Merged. Many thanks.

**Pull request merged**
