### PR TITLE
Added events support.

### PR DESCRIPTION
**Pull request by ilich**

### CODE REVIEW

**Comment by ppowalowski** [comment]
Hi! Thanks for your contribution 👍

**Comment by ppowalowski** [comment]
Would you mind giving some code examples for the readme?
Thank you sir!! Much appreciated

**Comment by ilich** [comment]
Hi! Sure. I will try to find time later this week or at the beginning of the next week. Thank you for the plugin. It saved me a ton of time. ;-)

**Comment by ppowalowski** [comment]
**Also:** Are you available to be added as collaborator to also create the appropriate Tag and update gh-pages?

Great to hear - Yes. I remember me searching for exactly this until I just rewrote another plugin to be exactly this hehe

**Comment by ilich** [comment]
Sure, why not.

**Comment by ppowalowski** [comment]
welcome on board 👍

**Comment by eballeste** [comment]
i was kind of excited when i saw that a resize event was added which can help solve some of the open issues but besides the fact that it's not documented and not very clear from the source code how to listen in on them, this PR also adds a bunch of unnecessary console.logs which are polluting the console

**Pull request merged**
